name: Test this and that on GitHub Actions

on:

  workflow_dispatch:
  push:

jobs:
  test_run:
    permissions:
      id-token: write # Enable OIDC
    runs-on: ubuntu-latest

    steps:
    - name: Setup gitsign
      uses: chainguard-dev/actions/setup-gitsign@main
